import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "@/src/providers/reactQuery/clientProviders";
import { AuthProvider } from "@/src/providers/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ClientProviders>{children}</ClientProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
